services:
  stats-server:
    build: stats-service/stats-server
    container_name: stats-service-container
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm-stat
      - SPRING_DATASOURCE_USERNAME=ewmstat
      - SPRING_DATASOURCE_PASSWORD=ewmstat

  stats-db:
    image: postgres:16.1
    container_name: postgres-ewm-stat
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_PASSWORD=ewmstat
      - POSTGRES_USER=ewmstat
      - POSTGRES_DB=ewm-stat

  ewm-service:
    build: main-service
    container_name: main-service-container
    ports:
      - "8080:8080"
    environment:
      - STATS_SERVER_URL=http://stats-server:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm-main
      - SPRING_DATASOURCE_USERNAME=ewmstat
      - SPRING_DATASOURCE_PASSWORD=ewmstat

  ewm-db:
    image: postgres:16.1
    container_name: postgres-ewm-main
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=ewmmain
      - POSTGRES_USER=ewmmain
      - POSTGRES_DB=ewm-main
