package ru.practicum.ewm.event.dto;

import com.fasterxml.jackson.annotation.JsonFormat;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import ru.practicum.ewm.category.dto.CategoryDto;
import ru.practicum.ewm.enums.State;
import ru.practicum.ewm.event.model.Location;
import ru.practicum.ewm.user.dto.UserShortDto;

import java.time.LocalDateTime;

@Data //Lombok, чтобы сгенерировать геттеры и сеттеры для полей
@Builder //создаёт через билдер произвольный конструктор
@AllArgsConstructor
@NoArgsConstructor
public class EventShortDto {
    private Long id;

    @NotBlank
    @Size(min = 1,max = 1000)
    private String annotation;

    @NotNull
    private CategoryDto category;

    private Long confirmedRequests;

    @NotNull
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private LocalDateTime eventDate; //Дата и время на которые намечено событие (в формате "yyyy-MM-dd HH:mm:ss")

    @NotNull
    private UserShortDto initiator; //Пользователь (краткая информация)

    @NotNull
    private Boolean paid; //Нужно ли оплачивать участие

    @NotBlank
    @Size(min = 1,max = 50)
    private String title; //Заголовок

    private Long views; //Количество просмотрев события

}

/*
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        annotation VARCHAR(1000) NOT NULL,
        category_id BIGINT NOT NULL references categories(id),
        confirmed_requests BIGINT,
    created_on TIMESTAMP WITHOUT TIME ZONE,

    description VARCHAR(2000),
        event_date TIMESTAMP NOT NULL,
        initiator_id BIGINT NOT NULL references users(id),
    location_id  BIGINT NOT NULL  references users(id),
        paid BOOLEAN NOT NULL,
    participant_limit INTEGER,
    published_on TIMESTAMP,

    request_moderation BOOLEAN,
    state VARCHAR(25),
        title VARCHAR(50) NOT NULL,
        views BIGINT
 */
